{"authenticity_token"=>"A2J3c+nQpmRUlMXDg9tyLeU8RFYG0fdNFCqRcj4UELM7F0UefCxu0fraflAsWsvf/Djq0GfcHuPamMUt0I9b+w=="
  #  "card"=>{"number"=>""
  #           "exp-month"=>""
  #           "exp-year"=>""
  #           "cvc"=>""}
    # "token"=> ""
    "post_code"=>""
    "prefecture_id"=>"0"
    "city"=>""
    "block_number"=>""
    "building_name"=>""
    "phone_number"=>""
    "controller"=>"purchases"
    "action"=>"create"
    "item_id"=>"17"
}